NREL/bifacial_radiance

- bifacial_radiance/bifacial_radiance.py
southern latitude test cases confirmed (South Africa, 0 azimuth)
> ascii encoding error in getEPW_all; allow all azimuth values

- bifacial_radiance/bifacial_radiance.py
- tests/test_bifacial_radiance.py
Hourly 1-axis tracking workflow completed.  Todo: Update readme files and examples to demonstrate new functionality.
> merge Hourly tracking branch into 0.2.3 release

- README.md
- bifacial_radiance/bifacial_radiance.py
Gendaylit still creates a sky for Sun below the horizon, but then Rtrace crashes. So added a variable to catch this and pass it forward.
It also checks if DNI is = or less to 0 becuase Gendaylit itself crashed on those instances for me.
Not sure if it's the most elegant way to handle these exceptions but it works :D
Addresses #41
> Gendaylit "Goodsky" Variable

- bifacial_radiance/bifacial_radiance.py
- setup.py
- tests/test_bifacial_radiance.py
@shirubana : I've greatly streamlined the code, so the solarposition calculation and time adjustment is done once in the very beginning when the MetObj is created.  This cleans up a lot of the calculations in getTrackerAngles and gendaylit.
> Get tracking angles

- requirements.txt
- tests/test_load.py
> add requests and future to reqs

- bifacial_radiance/main.py
- tests/test_bifacial_radiance.py
- tests/test_load.py
- tests/test_readepw.py
> RadianceObj.path absolute

- bifacial_radiance/main.py
- tests/test_bifacial_radiance.py
- tests/test_load.py
- tests/test_readepw.py
Reverts NREL/bifacial_radiance#134
> Revert "RadianceObj.path absolute"

- bifacial_radiance/main.py
- tests/test_bifacial_radiance.py
- tests/test_load.py
- tests/test_readepw.py
oops.  meant to base this on development, not master...
> Gh127 radianceobj path abs

- bifacial_radiance/main.py
- docs/sphinx/source/whatsnew/v0.3.4.rst
- tests/test_bifacial_radiance.py
> Met obj deltastyle

- bifacial_radiance/main.py
- requirements.txt
Tests are passing on my computer now - had to fix some string parsing details inside the code.  TravisCI is still not working...
> Development bugfix

- MANIFEST.in
- setup.py
Closes #275, and maybe #282?
Unsolicited PR, hopefully it's welcome.  I assume PRs go to the `development` branch.  Do you want a test or whatsnew entry for this?
> Update package_data and MANIFEST to include images folder

- .travis.yml
- bifacial_radiance/__init__.py
- bifacial_radiance/spectral_utils.py
- setup.py
- tests/test_spectra.py
Updates to spectral pipeline and introduction of pytests.  Fixes #287
> Spectra pytests

- bifacial_radiance/main.py
- bifacial_radiance/modelchain.py
- docs/tutorials/1 - Introductory Example - Fixed Tilt simple setup.ipynb
- docs/tutorials/1 - Introductory Example - Fixed Tilt simple setup.py
- docs/tutorials/2 - Introductory Example - Single Axis Tracking with cumulative Sky.ipynb
- docs/tutorials/2 - Introductory Example - Single Axis Tracking with cumulative Sky.py
- docs/tutorials/3 - Medium Level Example - Single Axis Tracking - hourly.ipynb
- docs/tutorials/3 - Medium Level Example - Single Axis Tracking - hourly.py
- docs/tutorials/4 - Medium Level Example - Debugging your Scene with Custom Objects (Fixed Tilt 2-up with Torque Tube + CLEAN Routine + CustomObject).ipynb
- docs/tutorials/4 - Medium Level Example - Debugging your Scene with Custom Objects (Fixed Tilt 2-up with Torque Tube + CLEAN Routine + CustomObject).py
- docs/tutorials/5 - Medium Level Example - Bifacial Carports and Canopies + sampling across a module!.ipynb
- docs/tutorials/5 - Medium Level Example - Bifacial Carports and Canopies + sampling across a module!.py
- docs/tutorials/6 - Advanced topics - Understanding trackerdict structure.ipynb
- docs/tutorials/6 - Advanced topics - Understanding trackerdict structure.py
- docs/tutorials/8 - Advanced topics - Calculating Power Output and Electrical Mismatch.ipynb
- docs/tutorials/8 - Advanced topics - Calculating Power Output and Electrical Mismatch.py
- tests/test_bifacial_radiance.py
Fixes #347 refactor ModuleObj.data to eliminate it.
> 347 module obj data

- bifacial_radiance/main.py
- bifacial_radiance/module.py
- docs/sphinx/source/whatsnew/v0.4.0.rst
- docs/tutorials/(debug) Module with all Bells and Whistles.html
- docs/tutorials/(debug) Module with all Bells and Whistles.ipynb
- docs/tutorials/(debug) Module with all Bells and Whistles.py
- tests/test_bifacial_radiance.py
- tests/test_modelchain.py
- tests/test_performance.py
This seems to be working now.  HPC is selected in two places now: when creating the RadianceObj and when creating the AnalysisObj.  HPC is passed automatically to MakeScene and MakeModule since these are called by the RadianceObj.
> Issue 364 hpc functionality improved

- bifacial_radiance/gui.py
- bifacial_radiance/main.py
> 369 main updates

- bifacial_radiance/data/module.json
> 386 modulefile

- .github/workflows/docker.yml
ghcr.io/${{ github.repository }}:latest
to
ghcr.io/nrel/bifacial_radiance:latest
> docker.yml L60 update

- .github/workflows/pytest.yaml
- docs/sphinx/source/user_guide/installation.rst
- docs/sphinx/source/whatsnew/v0.4.2.rst
Update Radiance installation instructions per issue #417
> 417 instructions

- .github/workflows/pytest.yaml
- docs/sphinx/source/user_guide/installation.rst
- docs/sphinx/source/whatsnew/v0.4.2.rst
Reverts NREL/bifacial_radiance#452
> Revert "417 instructions"

- bifacial_radiance/main.py
- bifacial_radiance/performance.py
- tests/test_bifacial_radiance.py
- tests/test_performance.py
CEC performance bugfix. Fixes #516.
> Enclose file names used for radfiles in quotes.  Fixes #523.  

- .github/workflows/docker.yml
- .github/workflows/pytest.yaml
- bifacial_radiance/main.py
- docs/sphinx/source/whatsnew/pending.rst
Same pull request as #517 but targets to Main instead of Development.
> 515 warnings main

- bifacial_radiance/main.py
- docs/sphinx/source/whatsnew/pending.rst
- requirements.txt
Some pytests are returning deprecation warnings due to new numpy pandas and pvlib release.
> Fix deprecations

- docs/sphinx/source/whatsnew/pending.rst
- setup.py
Fixes install issues if git is not present.
> 535 setuptools

- docs/sphinx/source/conf.py
- requirements.txt
> bump to pandas 1.4.4 and numba 0.58.1 in requirements.txt
